import { CardType } from "../Types/CardDataType";

export const cards: CardType[] = [
  {
    name: "섬도희 - 레이",
    img_url: "/Images/Sky_Striker/레이.webp",
    type: "monster",
    grade: 4,
    rare: "cross",
  },
  {
    name: "섬도희 - 로제",
    img_url: "/Images/Sky_Striker/로제.webp",
    type: "monster",
    grade: 4,
    rare: "cross",
  },
  {
    name: "섬도기동 - 링케이지",
    img_url: "/Images/Sky_Striker/링케이지.webp",
    type: "magic",
    rare: "secret",
  },
  {
    name: "섬도기관 - 멀티롤",
    img_url: "/Images/Sky_Striker/멀티롤.webp",
    type: "magic",
    rare: "super",
  },
  {
    name: "섬도기 - 샤크캐논",
    img_url: "/Images/Sky_Striker/샤크캐논.webp",
    type: "magic",
    rare: "rare",
  },
  {
    name: "섬도희 토큰",
    img_url: "/Images/Sky_Striker/섬도희토큰.webp",
    type: "token",
    grade: 1,
    rare: "secret",
  },
  {
    name: "섬도희 - 시즈쿠",
    img_url: "/Images/Sky_Striker/시즈쿠.webp",
    type: "monster",
    grade: 1,
    extra: "link",
    rare: "secret",
  },
  {
    name: "섬도술식 - 애프터버너",
    img_url: "/Images/Sky_Striker/애프터버너.webp",
    type: "magic",
    rare: "rare",
  },
  {
    name: "섬도기 - 위도우앵커",
    img_url: "/Images/Sky_Striker/위도우앵커.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "합체술식 - 인게이지 제로",
    img_url: "/Images/Sky_Striker/인게이지_제로.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "cross",
  },
  {
    name: "섬도기 - 호넷비트",
    img_url: "/Images/Sky_Striker/호넷비트.webp",
    type: "magic",
    rare: "secret",
  },
  {
    name: "섬도희 - 카가리",
    img_url: "/Images/Sky_Striker/카가리.webp",
    grade: 1,
    type: "monster",
    extra: "link",
    rare: "cross",
  },
  {
    name: "섬도희 - 하야테",
    img_url: "/Images/Sky_Striker/하야테.webp",
    grade: 1,
    type: "monster",
    extra: "link",
    rare: "super",
  },
  {
    name: "섬도희 - 지크",
    img_url: "/Images/Sky_Striker/지크.webp",
    grade: 2,
    type: "monster",
    extra: "link",
    rare: "super",
  },
  {
    name: "섬도희 - 카멜리아",
    img_url: "/Images/Sky_Striker/카멜리아.webp",
    grade: 2,
    type: "monster",
    extra: "link",
    rare: "cross",
  },
  {
    name: "미래의 주 - 키아노스",
    img_url: "/Images/Sky_Striker/키아노스.webp",
    grade: 1,
    type: "monster",
    rare: "ultra",
  },
  {
    name: "섬도기동 - 인게이지",
    img_url: "/Images/Sky_Striker/인게이지.webp",
    type: "magic",
    rare: "secret",
  },
  {
    name: "섬도희 - 카이나",
    img_url: "/Images/Sky_Striker/카이나.webp",
    type: "monster",
    grade: 1,
    extra: "link",
    rare: "super",
  },
  {
    name: "갑부 고블린",
    img_url: "/Images/Common/Magic/갑부고블린.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "무덤의 지명자",
    img_url: "/Images/Common/Magic/무명자.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "삼전의 재",
    img_url: "/Images/Common/Magic/삼전의재.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "삼전의 호",
    img_url: "/Images/Common/Magic/삼전의호.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "탐욕의 항아리",
    img_url: "/Images/Common/Magic/탐욕.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "증원",
    img_url: "/Images/Common/Magic/증원.webp",
    type: "magic",
    rare: "cross",
  },
  {
    name: "카이저 콜로세움",
    img_url: "/Images/Common/Magic/카이저콜로세움.webp",
    type: "magic",
    rare: "ultra",
  },

  {
    name: "원시생명체 니비루",
    img_url: "/Images/Common/Monster/니비루.webp",
    type: "monster",
    grade: 11,
    rare: "secret",
  },
  {
    name: "원시생명체 토큰",
    img_url: "/Images/Common/Monster/니비루_토큰.webp",
    grade: 11,
    type: "token",
    rare: "secret",
  },
  {
    name: "이펙트 뵐러",
    img_url: "/Images/Common/Monster/이펙트뵐러.webp",
    type: "monster",
    grade: 1,
    rare: "ultra",
  },
  {
    name: "증식의 G",
    img_url: "/Images/Common/Monster/증식의G.webp",
    type: "monster",
    grade: 2,
    rare: "secret",
  },
  {
    name: "하루우라라",
    img_url: "/Images/Common/Monster/하루우라라.webp",
    type: "monster",
    grade: 3,
    rare: "secret",
  },
  {
    name: "화령술사 히타",
    img_url: "/Images/Common/Extra/히타.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
  },
  {
    name: "수령술사 에리아",
    img_url: "/Images/Common/Extra/에리아.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
  },
  {
    name: "지령술사 아우스",
    img_url: "/Images/Common/Extra/아우스.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
  },
  {
    name: "암령술사 달크",
    img_url: "/Images/Common/Extra/달크.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
  },
  {
    name: "광령술사 라이너",
    img_url: "/Images/Common/Extra/라이너.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
  },
  {
    name: "풍령술사 윈",
    img_url: "/Images/Common/Extra/윈.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
  },

  {
    name: "액세스 코드 토커",
    img_url: "/Images/Common/Extra/토커.webp",
    type: "monster",
    grade: 4,
    extra: "link",
    rare: "cross",
  },
  {
    name: "트리온의 충혹마",
    img_url: "/Images/Traptrix/트리온.webp",
    type: "monster",
    grade: 4,
    rare: "super",
  },
  {
    name: "티오의 충혹마",
    img_url: "/Images/Traptrix/티오.webp",
    type: "monster",
    grade: 4,
    rare: "super",
  },
  {
    name: "란카의 충혹마",
    img_url: "/Images/Traptrix/란카.webp",
    type: "monster",
    grade: 4,
    rare: "super",
  },
  {
    name: "지나의 충혹마",
    img_url: "/Images/Traptrix/지나.webp",
    type: "monster",
    grade: 4,
    rare: "super",
  },
  {
    name: "푸티카의 충혹마",
    img_url: "/Images/Traptrix/푸티카.webp",
    type: "monster",
    grade: 4,
    rare: "super",
  },
  {
    name: "키노의 충혹마",
    img_url: "/Images/Traptrix/키노.webp",
    type: "monster",
    grade: 4,
    rare: "ultra",
  },

  {
    name: "드롤 & 로크 버드",
    img_url: "/Images/Common/Monster/드롤로크버드.webp",
    type: "monster",
    grade: 1,
    rare: "secret",
  },
  {
    name: "D.D. 크로우",
    img_url: "/Images/Common/Monster/DD크로우.webp",
    type: "monster",
    grade: 1,
    rare: "secret",
  },
  {
    name: "디멘션 어트랙터",
    img_url: "/Images/Common/Monster/디멘션어트랙터.webp",
    type: "monster",
    grade: 6,
    rare: "cross",
  },
  {
    name: "유령토끼",
    img_url: "/Images/Common/Monster/유령토끼.webp",
    type: "monster",
    grade: 2,
    rare: "cross",
  },
  {
    name: "저택 와라시",
    img_url: "/Images/Common/Monster/저택와라시.webp",
    type: "monster",
    grade: 2,
    rare: "cross",
  },
  {
    name: "쿠리카라 천동",
    img_url: "/Images/Common/Monster/쿠리카라천동.webp",
    type: "monster",
    grade: 2,
    rare: "cross",
  },
  {
    name: "다이나레슬러 판크라톱스",
    img_url: "/Images/Common/Monster/판크라톱스.webp",
    type: "monster",
    grade: 2,
    rare: "cross",
  },
  {
    name: "크샤트리라 유니콘",
    img_url: "/Images/Common/Monster/크샤트리라_유니콘.webp",
    type: "monster",
    grade: 2,
    rare: "cross",
  },
  {
    name: "크샤트리라 펜릴",
    img_url: "/Images/Common/Monster/크샤트리라_펜릴.webp",
    type: "monster",
    grade: 2,
    rare: "cross",
  },

  {
    name: "세라의 충혹마",
    img_url: "/Images/Traptrix/세라.webp",
    type: "monster",
    grade: 1,
    extra: "link",
    rare: "cross",
  },
  {
    name: "클라리아의 충혹마",
    img_url: "/Images/Traptrix/클라리아.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "cross",
  },
  {
    name: "아티푸스의 충혹마",
    img_url: "/Images/Traptrix/아티푸스.webp",
    type: "monster",
    grade: 3,
    extra: "link",
    rare: "cross",
  },
  {
    name: "여휘사 벨즈뷰트",
    img_url: "/Images/Common/extra/여휘사.webp",
    type: "monster",
    grade: 4,
    extra: "xyz",
    rare: "secret",
  },
  {
    name: "크로노다이버 리단",
    img_url: "/Images/Common/extra/리단.webp",
    type: "monster",
    grade: 4,
    extra: "xyz",
    rare: "cross",
  },
  {
    name: "No.41 이수마수 바구스카",
    img_url: "/Images/Common/extra/바구스카.webp",
    type: "monster",
    grade: 4,
    extra: "xyz",
    rare: "secret",
  },
  {
    name: "로기어스텔라 티 폰",
    img_url: "/Images/Common/extra/티폰.webp",
    type: "monster",
    grade: 12,
    extra: "xyz",
    rare: "cross",
  },
  {
    name: "네가로기어 아제우스",
    img_url: "/Images/Common/extra/아제우스.webp",
    type: "monster",
    grade: 12,
    extra: "xyz",
    rare: "cross",
  },
  {
    name: "에스:피 리틀나이트",
    img_url: "/Images/Common/extra/리틀나이트.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "cross",
  },
  {
    name: "트로이메어 유니콘",
    img_url: "/Images/Common/Extra/유니콘.webp",
    type: "monster",
    grade: 3,
    extra: "link",
    rare: "secret",
  },

  {
    name: "사로스=에레스 쿠르누기아스",
    img_url: "/Images/Common/extra/사로스.webp",
    type: "monster",
    grade: 5,
    extra: "link",
    rare: "cross",
  },
  {
    name: "플레시아의 충혹마",
    img_url: "/Images/Traptrix/플레시아.webp",
    type: "monster",
    grade: 4,
    extra: "xyz",
    rare: "secret",
  },
  {
    name: "시트리스의 충혹마",
    img_url: "/Images/Traptrix/시트리스.webp",
    type: "monster",
    grade: 4,
    extra: "xyz",
    rare: "cross",
  },
  {
    name: "충혹의 동산",
    img_url: "/Images/Traptrix/동산.webp",
    type: "magic",
    rare: "ultra",
  },
  {
    name: "충혹의 동산",
    img_url: "/Images/Traptrix/홀티아.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "해피의 깃털",
    img_url: "/Images/Common/Magic/해피의깃털.webp",
    type: "magic",
    rare: "secret",
  },
  {
    name: "나락의 함정 속으로",
    img_url: "/Images/Common/trap/나락의함정속으로.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "연옥의 함정 속으로",
    img_url: "/Images/Common/trap/연옥의함정속으로.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "전망의 함정 속으로",
    img_url: "/Images/Common/trap/전망의함정속으로.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "이차원 그랜드",
    img_url: "/Images/Common/trap/이차원그랜드.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "충혹의 함정 속으로",
    img_url: "/Images/Common/trap/충혹의함정속으로.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "팬텀 나이츠 셰이드 브리간딘",
    img_url: "/Images/Common/trap/브리간딘.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "절망의 함정 속으로",
    img_url: "/Images/Common/trap/절망의함정속으로.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "길항승부",
    img_url: "/Images/Common/Trap/길항승부.webp",
    type: "trap",
    rare: "rare",
  },
  {
    name: "무한포영",
    img_url: "/Images/Common/Trap/무한포영.webp",
    type: "trap",
    rare: "ultra",
  },
  {
    name: "무덤 홀",
    img_url: "/Images/Common/trap/무덤홀.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "천룡설옥",
    img_url: "/Images/Common/trap/천룡설옥.webp",
    type: "trap",
    rare: "cross",
  },
  {
    name: "광혹의 함정 속으로",
    img_url: "/Images/Common/trap/광혹의함정속으로.webp",
    type: "trap",
    rare: "super",
  },
  {
    name: "신의 심판",
    img_url: "/Images/Common/trap/신의심판.webp",
    type: "trap",
    rare: "cross",
  },
  {
    name: "마법 봉인의 방향제",
    img_url: "/Images/Common/trap/마봉향.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "강제 탈출장치",
    img_url: "/Images/Common/trap/강제탈출장치.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "메타버스",
    img_url: "/Images/Common/trap/메타버스.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "격류장",
    img_url: "/Images/Common/trap/격류장.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "신의 통고",
    img_url: "/Images/Common/trap/신의통고.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "왕궁의 철벽",
    img_url: "/Images/Common/trap/왕궁의철벽.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "이세상너머",
    img_url: "/Images/Common/trap/이세상너머.webp",
    type: "trap",
    rare: "secret",
  },
  {
    name: "차원장벽",
    img_url: "/Images/Common/trap/차원장벽.webp",
    type: "trap",
    rare: "secret",
  },
];
