import { CardType } from "../../Types/CardDataType";

// 섬도희 데이터

export const Sky_Striker_Main: CardType[] = [
  {
    name: "섬도희-레이",
    img_url: "/Images/Sky_Striker/레이.webp",
    type: "monster",
    grade: 4,
    rare: "cross",
    quantity: 3,
  },
  {
    name: "섬도희-로제",
    img_url: "/Images/Sky_Striker/로제.webp",
    type: "monster",
    grade: 4,
    rare: "cross",
    quantity: 1,
  },
  {
    name: "섬도기동-링케이지",
    img_url: "/Images/Sky_Striker/링케이지.webp",
    type: "magic",
    rare: "secret",
    quantity: 3,
  },
  {
    name: "섬도기관-멀티롤",
    img_url: "/Images/Sky_Striker/멀티롤.webp",
    type: "magic",
    rare: "super",
    quantity: 1,
  },
  {
    name: "섬도기-샤크캐논",
    img_url: "/Images/Sky_Striker/샤크캐논.webp",
    type: "magic",
    rare: "rare",
    quantity: 1,
  },
  {
    name: "섬도희 토큰",
    img_url: "/Images/Sky_Striker/섬도희토큰.webp",
    type: "token",
    grade: 1,
    rare: "secret",
    quantity: 1,
  },
  {
    name: "섬도희-시즈쿠",
    img_url: "/Images/Sky_Striker/시즈쿠.webp",
    type: "monster",
    grade: 1,
    extra: "link",
    rare: "secret",
    quantity: 2,
  },
  {
    name: "섬도술식-애프터버너",
    img_url: "/Images/Sky_Striker/애프터버너.webp",
    type: "magic",
    rare: "rare",
    quantity: 1,
  },
  {
    name: "섬도기-위도우앵커",
    img_url: "/Images/Sky_Striker/위도우앵커.webp",
    type: "magic",
    rare: "ultra",
    quantity: 3,
  },
  {
    name: "합체술식-인게이지 제로",
    img_url: "/Images/Sky_Striker/인게이지_제로.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "cross",
    quantity: 1,
  },
  {
    name: "섬도기-호넷비트",
    img_url: "/Images/Sky_Striker/호넷비트.webp",
    type: "magic",
    rare: "secret",
    quantity: 1,
  },
  {
    name: "섬도희-카가리",
    img_url: "/Images/Sky_Striker/카가리.webp",
    grade: 1,
    type: "monster",
    extra: "link",
    rare: "cross",
    quantity: 3,
  },
  {
    name: "섬도희-하야테",
    img_url: "/Images/Sky_Striker/하야테.webp",
    grade: 1,
    type: "monster",
    extra: "link",
    rare: "super",
    quantity: 2,
  },
  {
    name: "섬도희-지크",
    img_url: "/Images/Sky_Striker/지크.webp",
    grade: 2,
    type: "monster",
    extra: "link",
    rare: "super",
    quantity: 1,
  },
  {
    name: "섬도희-카멜리아",
    img_url: "/Images/Sky_Striker/카멜리아.webp",
    grade: 2,
    type: "monster",
    extra: "link",
    rare: "cross",
    quantity: 1,
  },
  {
    name: "미래의 주-키아노스",
    img_url: "/Images/Sky_Striker/키아노스.webp",
    grade: 1,
    type: "monster",
    rare: "ultra",
    quantity: 1,
  },
  {
    name: "섬도기동-인게이지",
    img_url: "/Images/Sky_Striker/인게이지.webp",
    type: "magic",
    rare: "secret",
    quantity: 3,
  },
  {
    name: "섬도희-카이나",
    img_url: "/Images/Sky_Striker/카이나.webp",
    type: "monster",
    grade: 1,
    extra: "link",
    rare: "super",
    quantity: 1,
  },
  {
    name: "갑부 고블린",
    img_url: "/Images/Common/Magic/갑부고블린.webp",
    type: "magic",
    rare: "ultra",
    quantity: 3,
  },
  {
    name: "무덤의 지명자",
    img_url: "/Images/Common/Magic/무명자.webp",
    type: "magic",
    rare: "ultra",
    quantity: 2,
  },
  {
    name: "삼전의 재",
    img_url: "/Images/Common/Magic/삼전의재.webp",
    type: "magic",
    rare: "ultra",
    quantity: 1,
  },
  {
    name: "삼전의 호",
    img_url: "/Images/Common/Magic/삼전의호.webp",
    type: "magic",
    rare: "ultra",
    quantity: 1,
  },
  // {
  //   name: "탐욕의 항아리",
  //   img_url: "/Images/Common/Magic/탐욕.webp",
  //   type: "magic",
  //   rare: "ultra",
  //   quantity: 1,
  // },
  {
    name: "증원",
    img_url: "/Images/Common/Magic/증원.webp",
    type: "magic",
    rare: "cross",
    quantity: 1,
  },
  {
    name: "카이저 콜로세움",
    img_url: "/Images/Common/Magic/카이저콜로세움.webp",
    type: "magic",
    rare: "ultra",
    quantity: 1,
  },
  {
    name: "해피의 깃털",
    img_url: "/Images/Common/Magic/해피의깃털.webp",
    type: "magic",
    rare: "secret",
    quantity: 1,
  },
  {
    name: "원시생명체 니비루",
    img_url: "/Images/Common/Monster/니비루.webp",
    type: "monster",
    grade: 11,
    rare: "secret",
    quantity: 1,
  },
  {
    name: "원시생명체 토큰",
    img_url: "/Images/Common/Monster/니비루_토큰.webp",
    grade: 11,
    type: "token",
    rare: "secret",
    quantity: 1,
  },
  {
    name: "이펙트 뵐러",
    img_url: "/Images/Common/Monster/이펙트뵐러.webp",
    type: "monster",
    grade: 1,
    rare: "ultra",
    quantity: 2,
  },
  {
    name: "증식의 G",
    img_url: "/Images/Common/Monster/증식의G.webp",
    type: "monster",
    grade: 2,
    rare: "secret",
    quantity: 3,
  },
  {
    name: "하루우라라",
    img_url: "/Images/Common/Monster/하루우라라.webp",
    type: "monster",
    grade: 3,
    rare: "secret",
    quantity: 3,
  },
  {
    name: "무한포영",
    img_url: "/Images/Common/Trap/무한포영.webp",
    type: "trap",
    rare: "ultra",
    quantity: 2,
  },
  {
    name: "길항승부",
    img_url: "/Images/Common/Trap/길항승부.webp",
    type: "trap",
    rare: "rare",
    quantity: 1,
  },
  {
    name: "화령술사 히타",
    img_url: "/Images/Common/Extra/히타.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "ultra",
    quantity: 1,
  },
  {
    name: "에스:피 리틀나이트",
    img_url: "/Images/Common/Extra/리틀나이트.webp",
    type: "monster",
    grade: 2,
    extra: "link",
    rare: "secret",
    quantity: 1,
  },
  {
    name: "트로이메어 유니콘",
    img_url: "/Images/Common/Extra/유니콘.webp",
    type: "monster",
    grade: 3,
    extra: "link",
    rare: "secret",
    quantity: 1,
  },
  {
    name: "액세스 코드 토커",
    img_url: "/Images/Common/Extra/토커.webp",
    type: "monster",
    grade: 4,
    extra: "link",
    rare: "cross",
    quantity: 1,
  },
];
